# Generated by Django 5.0 on 2024-01-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="Dapp.tags"),
        ),
    ]
